apiVersion: apps/v1
kind: Deployment
metadata: 
  name: batch13-deployment
  namespaces: batch13
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: batch13-nginx
  template:
    metadata:
      lables:
        app: batch13-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
            


