apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespaces: batch13
spec:
  type: NodePort 
  selector:
    app: batch13-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30080
